### ISSUE TITLE
No display of Health Date

### ISSUE THREAD

**Issue by Steinmeier68** [meganmakela/weather-cal#2] opened 2021-01-01 18:37 UTC
Hello, it only ran for a short period of time for me, all paths are set correctly, but no data from the health app is displayed, the rest works and I cannot find the error

**Comment by meganmakela** [comment] 2021-01-03 22:13
I would check the Health Export app itself and the files on the iCloud Drive. Try forcing a sync, it just might not be exporting in the background frequently because of limitations by Apple itself. Read the Health Export dev website for more info on that.

**Comment by Steinmeier68** [comment] 2021-01-04 07:51
Good morning and thanks for your answers, I checked the data in the iCloud, you have the correct file name and the backup is automatically synchronized. I've already tried it for testing on the iPad, without success. As soon as I change the "Formating Name" "const formatDate = y +" - "+ m +" - "+ day" in the script, I get an error message. This means that he cannot find the file, so the file is there, but it is not displayed.
<img width="883" alt="Bildschirmfoto 2021-01-04 um 08 41 51" src="https://user-images.githubusercontent.com/76256660/103512957-f5f5ee80-4e69-11eb-9fab-38c5c826b948.png">

**Comment by meganmakela** [comment] 2021-01-04 15:26
Thanks for checking, I see what the issue is. The app saves with path and file name formatted as "YYYY-MM-dd" and right now the script is only set to handle "YYYY-M-d". Should be easy to generate an ugly but functional fix for numbers < 10 vs numbers ≥ 10. I'm back at work from the holidays but can get to it in the next few days, if you can't figure out a fix yourself.

**Comment by Steinmeier68** [comment] 2021-01-04 15:58
thanks for the answer, I've already tried something in the script, yyyy-MM-dd, YYYY-mm-dd. Unfortunately all without success. I wish you a nice vacation

**Comment by Steinmeier68** [comment] 2021-01-09 16:05
Hello, did you find a solution yet?

**Comment by skaterule** [comment] 2021-01-18 18:35
Same Problem here. I hope there is any Solution. Would be great to use the health data :)

**Comment by meganmakela** [comment] 2021-01-19 03:39
@Steinmeier68 @skaterule Should be fixed now!

**Closed as completed by meganmakela** 2021-01-19 03:39 UTC

**Comment by skaterule** [comment] 2021-01-19 10:52
Yes! Thank you! :)
